### ISSUE TITLE
facter is not idempotent

### ISSUE THREAD

**Issue by DavHau** [nix-community/nixos-facter#207]
Generating `facter.json` twice on the same machine gives me different results:

[Click for diff](https://json-diff-share.com/diff?content=eJztfWlz2zi29l9R6XNsEwTXfPOS6c5MnM5td-ZO3SkXiyIpi6-5NUl56Zn89xcH4AIuoESJtmXHqe5EBEkQyznPWQCc85954C3z-cf_zFd26t7bqQe_F36cwb92Elp-tIzLMmsZ2DfkjvRh7kX2IvDc-celHWTeh3m2Xlh3Xpr5cUTvZ-skidOce6K---PDPFjYVvFI9UAQ31uhF8bpo5X5f3m0miRKqvvkt-W7rPaQNqeqUtdV8oGFV7WWb8qd73pxUTN8nXx-kfruDfnCv0kf89x2Vp5r5eRFlTy-sDPPcgI7o0Ow8h7mH-eSJGnzD_PIDslL8zP2NqnZDtakQIMa15mVPyZe4x2lfufb-ef6BYW8QL9gBX5GBuDf88Tx51Wzrj_MXS-3_QAqc-IwtCPSbf3DfLmOnLzs1sqzXS8tPoo-zP30z_lH2SDjlMY3lr9kA-U5ceTaZEhJA9mHXe_Od7h2Knip1E1DOjahP27qkzEkt0nLPDpNZZkVxu468LhbbnrXvpsVnaruX5cPNO5AsR-50A6sfZiTdz3S6fnp5cWMDNhsUQ40q9SyA9_O2Ic_3pHxlZAkyy78UPDflIwVnckoo2UYy8bCkbTMkRRfkkg15D1CIbmXLm2nOVNSPVNf4zS0g5lLRs7lJhmoNvWyeJ06tHf_oYTCRrxihjxdE0LNU__mxks9Rqtsguj0_LiGOu58Rprc5xE3AeQ7WRBTnqRzhknL1uECJgPaAIzWpc4mpdUDxxEcvNieexgi7tNYonPPeDly47R-Ei1krpGaqajw4GO2zICyKF_Scfwo4Y-SdAzjye7SOyfsw9kJmQH2lHRS_PtRko_RSf-rhPTX1k0arxnjI2DydrsIBdR9J4TDdZr0hzB7i8UPmMOlIQ6XCg6XBhlc6mFwpLh23TIVY-NHzXVGk-t-jbN8BNsh5eKUsR38YWwHfwq2kxjbNchZqsnZEJIzx47NFnHM2Et85D9jFPEZA_Rm_ETkhickNw_z5KbovDi5RVLuhUmPNBHcofKivNeUIlxpSc7mnuT8Ce9OzrLyFPSMjGO8PT03n27jp_wTETSakqBRg6DVGj8VtC_BoQMkODSK4NA7wT2fwFbwCwps9CQCG40S2GhIQZyA3MAOOVR6QxJG21iBijxIc3q_Fag2rcCG2H4uK1DZ1wpUX8YKhBF_UitQ4WD_NViBCth1-1iBJ_31tDn-Z9LRn0nC6C8oYZ5Eo5GUUZSoDNCb_rbJDTwsT2ET6qbE9YUAjClxBNfyQXy-Oh1Bb6TqT1lVlFVlBb0hRm99eKtyUGZ0AJfXs8V-N1SPfqPZPIz3IG7_ePQi7gbqEqvxyii7URmyG6fQqw6Z6ltqVdt0LNUqrA4SPu4H2kUDaM2X0KpgWWN3rYog-lmbw5Ci4qfXqmDAx2hVQgaeWmOC7nPTKkt4avYFfWic9iRk3zfuNW9zb1tqVdyrD3Iv6lsbI-zrNlw_6EXYV96TfS-67Htx8Qzsq0_DvuJ1gp3Zt2dap2XfUV5badBrK71t_m2YONqUXluNn2OV0zjVfZ1on7QD9Npqo7y2mpjgpvDavgk3mjYsMfrI7kD8aKrySv1o2vP50SYXK0_kRxu3oC32ow0tdctv3XW-1e4pWD4eYnj5gBlefZ0MD0P-XAyP8CvheHcijneHOB7_RGrlpJ5zbsZVjDVOrdT29ZwbPYaasZ1aKfZRbqVV9ltJ3a5OayWN2yg4tDfwjRtJW7soN6isAh_lITg59Ffq5Bipsb4tJ8cYH-XQTiHzbbNvQxgpU_o4lMYUc8u46r47ez8pB-jjUEb5OBQhvb31nWlbO8WVQaLrM3gOZEnLfKVLWso04kK8Fe9wl7TQKJ84GvCJT2G7HLK3YmsP5bDM0A7XX6Gh1-mvUKRn9Fe8EnfFuA28YnfF4NbeN77z6gU2-mnyC270E7vi9tnoh0dRIh6gN-0nIjd5SoNEbhgknHdMU_Y1SOQDNEjkUQaJLMa3n8wgETqw8LAD62ANEm2vBZgXNEjwz2yQjPFfoQH_1fuWicIgGd4iax6wQfJaTx6N3CO7j0EiFqKHZZCMO-8hNkiGToLIb3zF6ckMEk9qaIgKpyHu7bKWDlBDHEGKaGiLzpvfljdFgCPUpyAeiITR9zqF8XIS5skjHPEur9dyuNWZSMQ4QyLmrXP8tlolHmZ69YB5fq-jGy-4Le8Zef5VRDVT9o1qdtJfT1vI_0x-x-dxc-v7-h33cXOLxdk-bu6xkRXE9Kb8ROSmT2nE6Dy5qYgjN3VfI0Y_QCNGH2XE6GJ8e1dpCkfZ8MYb44BVmr02ar6go2zkzpt9VJrXctBg3HqpWKUZWklFP9PeTnVKGcNxu4oVk5MxezvK1AOUMeooGaOKCW4XGUPm1knWLCK46xL8yGgQctq_ZPWY-Y4Noy09YOq-9NN8XReQbtmps_Jzz8nXEEJ9_mBolgZktohvCPka2MDHAJyL9Q3FVdLy1Mst8hVC5gRqSV8S8nLqWXeIv5CLCyvLY3K9eExgzElZmsVAjw6wCEgdWSkuYN5votCLcrbk7gTLYJ2tipDqtITUlDFTg3TZd63AuwNSgoKlHfrBI5lkCATk2dAb2t4lGRvS7RAmk4JtksHfeeYAwWUplNiU-Bz423kAtLITH25nHgR1DfOUPsVI1AF13QnjO_pizirEwMtFe-Gh8IH8vXygtWf0e-RvGJFVziafzEkAs_rAnvYe8uIFK05onW7ioRtYHE5d0lRoRhDCN-Ioy-0ot1j7Uy-xbuIYdsvbIRmORcoGPooTqP4hj5M4iG8eaRF5M06KF-nwkX_Jh10Lekuv7ITIrRD-grptWkcS-VSsBeE6-NP9k3Jp5JM5pZ3KaMTcZUgH5QFprKeKhcofMn3hbkFHPk6cCHpne0AJD5l9B8X2HR0tpNEeuSlgE-muvVparM9hQib6xnagG9ldyJpdTJGTGvVNexEW34X2hH5GKYpNAHaj-D5JvaWXOzBHcXZ3T_7xF5Qob33SJ_Lj3oW_c0oKMHhsYmBECFVbQH_cZQTzs0iazwQBJax7288f6EDDQ46dWwGMlOMm7Mfq3krITOaMNhbQ43BhF_WQEWbz6C8oh_kLWkuWkx9FqeVFKztyPHpQIgwLelpmNxnVGUi7Qh-xwaWcGFJSJoVw5aUhrTa6S9jEO3-GjNQsm72jInlZ_aKznrqZR79muw-0QjupHvALAmAMwCjYCe4X1QMOvJitbIsSEytb3Fc_74KSHNi79CcM48ONly8ortCijDW1GGP4FTsOwc76OlyEROrmdsBdB7FDr9cZEW7ZKstvqw9biyVirPuXl8YwJGlB_fR7XprkKe17kgKK3C-imAwaHbEkgW_aKYWAiDabsN8dI1H4JnwlSv3EKsicMJ4FfE-lSuiAFPLsCCYNBm3xaGd0KphSSLCSyPGMYgxp99IPiEoJV8t8RYBtFQd0Ku4oD9zd-LTJcnltUeAl1AjdvovCetDvFvRiHfo0-DSAY6FRkp-W9-B4CVMHWGEhqk0IQFOIkvLMWhLfgypuR_aNxzD733Pa4DwHwshDSuQVjTM-8JZLa5l6f1p0sP-N8DX9R7mGxmT-IvAjkDJYBmL3koRc0h0KebAoxABWDSII1oRbi-eYvLRK-bjOV6QxvsME5X1KJJtF9BeQb0U6DhCYrp_ddnNoQCjMXl0N8braJbk3uyIASDo-u2C6TyWSZU0WqG4mV8XXf15-qt9BNMBHU3ujDSQVAR2VKjV5HcTYdVfjsg3Jrmu_Or28-v71l9nl__3PFxn9Yf56_vffjyTpVOIsfwVLyOBtsKiQkC37q6-YitWqKbXFVRYVqp7BLRoNNqlp8jiPAVQAVSIDIwVWq2-8uBjPOZFmPmNn0FYzphcQpZTMR0k4lE6IegPqTvEWDKdFapmDel6U0ecYKcFVUUUxQkSAfcS6KumKYUCUP1YoE3UWyXQvkZf6VIu60pRfvv4i_UuRTUWn3oN9TrlesGnfcLzVtiWbn0oVC2PwKQp_kg5Ru7ulx8K01TYQ-xahw-h2k1GFjnFxITOjCmo6aVbH9GHa5xNKzOx-hNjIP5TfK_oP3xt4gpIZfQYm9GTxeOS79PGjgsCsLoFZnRnarwKq2vRW4a39Y6xhRdGxRFCKPi1JsooNRS_sFK39LtEgVzC4R_xAHtHqqu-U43HdGpCCsP4zD-3_B5Mu05NFfgS_Eehv0Y3HuQdM4PctCKRjwSrmOyxOCIvop4NFcwAWtwrM_lKwiHaDxdLXhFqw2N6y2YZFtBEW-5_YHxbNfWHRHAWL5khYRCJYRCNhUdoDFsl3bohNvPKdzHLs1O3JwaYLfX24QcxJYD_OiCmfp3EQUL2--BLe3-_XbCN1SAvcf3ibFU20YVt7rwNQUzjsV3XEBbDT-QB2f3ye_fOXUzISIZlwov17zUERuwOlwh2oKVUEZance07KFo6Ea3fgVi550o4mwjTh13bIL2hESgbJombF_EPhnld13OOhL-hMhtAqpX-eAS17C43avv6h3YQ4Ch6rFiDJ0CTDNFTF1LtBHSqnBwE1MLvKlmkGwUiFa1_ohdt8iZhgsikpuJs4QPQlydQRhAId_E5zUBWENQ3LWO6eWhR8RZUV2TCaHxEshjgmp5pIneUQtFXiuibxCIl4g9Dq5ZX-swIS7wcmrPOH56wicO_5Xjb7HDkcKkgU1Xod1u7Y7SBGJc_ar7Y3ffUuyY9sNUzZar3ogqsmAlfEK3m_rrkDNbImWkcxOK3z-9UZp3TiLqKuM6gTGtXA0ULedAnDrOte8c2pjxBQj0TsxAEF4aKMTPogkSUEm2sYaxBWVUywkvyK7JxU5-U5dZ9I_P1xra3fq9iBL6x70SjeuSM9oqQpOh9-Pf_MlozOBcKzUtxZX9p6O5nKwofbVd3Le03tvZj2VZwnwfqGVTGvlXluk9wXP1o_zLRjpBwjafawItrLynFngja3ZBup9eMdutDOEuixK2lIcR3JdEGKuYmEfXLhU5FGHvAjYWYAfpyhKS0AKtVzjp-VTT6LJohoR9LHcaemW_ihnJC-aid1PR3IcLVF3Yn-Ua27pasY9Zis6psEC_QOFhvAQt4WLOQXAAv8FGAhd8AC9YNFY18JdZ-Dzk8sgWxl3zKNP7GJDvbI1PwEVns-KkZhooFDPk6s6sVCy1rYa1e852Q0GOFxYIT3BSMMYIRP8JOCkSb2n72D0TsYvRAYKe9gJAYjr7J0tgcjfQcwKhdQ2PcAjPQT_V0zejejfjIzSnv1ZtRIzUWZRHNRTpR3zeUdLF4YLERMrb9mpt5FAzAm0QCME-NpNQDlTTL1uznyqs0R490cEYPRYgcwQqPBaPCo_wnfEoApdIKeVvd4m-s97zD1qmHKfIepadeT1EnWk9QT9V1nejeEfi6viYles4G1i04jP7FOI5_Ik8IImbtb73ER9-4WBJVXgClG_aF_lO9zwKJMASy3dcVAVduhy3aI0MEZ6aVxhmPjle82uXZrnEEbcQbVnyFC1Y-5GejHF5nr-rcrOY_JtM1OXTvJG9jS0HTIbLE-FCjiR8sY6izEOTevD7cLqwSIxEF0EymUpQx15g_L1PMI0fzoxarGR5pQBbeaSFUXisCKOw30y-nV59NZT3_7cEn6ZPwtgZFyyf_IBUgqcEkiuIQBl5APGtNeShJSJ1GR5GM-zoLU3lg49jhQl_l7DT305IYe_b_4imh_uh8l6_zEI7iZ9z1Wb1JnD7Id4qT-I0oOVkkOVkEOR7Smo1t6NLb5Xmt3OGvqEVRFwBtaucu7d_Kmt4uuXW_Ybw67R4vt5nAIo9idiqr95qDbtIWL5BnLetrpgHDsr8ts-3nohXH62JUkohATiAekzxEFzSB4nH3PPHd2HrDz-KVUUfWOiCi-d10xMeYiBF3afjS7ZE-M2S09uJ93Hd1G8T0cii2HDStI1rAma7C7tLV_uHpGV7BhqljR6z3GcFzVKvcA9zMaZ2g2O1PZl3TQ4zU0e4T0Vrl66cuc6EZTiO6wqLWQ22zncbWzeP6LFxFVy5kBtpYNKJ4p6W7-vRrod6lfnkTql_ryYUv9xTrP44g06Ag8SwuLQFT6aElAJt5DEhCbIk2yE3ro_yHJZKCXmyQkFbLLmqcKQrlfeV5QVPewJGT5sVnPc-gKhvq0uoJMdAX0JnQF3ECNWQtusEhZGJM7YHdlYegwG5OoITu_2X5Ibj0FvdpGpaDVjRHPWCCeuxXI_TXAGZgJBXzk5fdxemtxB0i65yCQ8JAZJ9C-spp6j6KIjuKOOGTW09Chk2abQsuVh802ZLHvPWumYj7XhiI3Isv5N32OmJ5SSkpQ3oSqoqSM8s7ZMKBOBbNP-YrIJC_f7tyaQcQ8O6NGGl2cWzMUM6vKFo4k1-fWWjoVi-3EThkWWLO6h9KNZ6k0pPQkfyvoFsv959NGpbfffJjL1HVDUrqxeUcc5tr4EUXCkox70hoLPoI0bHS1yr6BTsqRFuE6bqEuj-TaSKuvn6g2nSPr44Pec2SE4uoHNRn1nH1mqK5NFzgYVRftSnuS5fXIDC9KtEwoAoq7113YNRqKNePZ8zhN4tSmSMQpW6YkNzCYOzG6vb2ldxH4c1evJQaNEFHrz9a4Y_KnjOI4WdjO7ax4YcbrzRtJq3y7z6HAn0knlZ8Ecb_87i2n80DuXHfXcZ9ttJ4I9U3u2EbFmn2jPw6vN6BM_1SiLkrw1sYO0Qp24dkWoQiZc2vGhQ6D9jDmRD2nrFyug9wPPde3eyFT5C4fHUyz9E70Kzn6NtE0kTqcEKBfxWmkJtSkhmGYRa6VJoEFp9xtJ9Eeekh_4zN0NrpPNdmi937BJEorQ4hoSjZH-FTLZIlcOjlSRlQjJXOMXtWoOJqujon8v1lj0ZGqadLWGotMRKmibHX8XOOmkx3UHn363JC2Jn8kG0KdoYewJsxTR9fnR8RGbS_tiwOlQmKXJ4zMy62_lc400o7cC2cJuUgI8NJQO0XtxvPgC4uUujn3Kd4pCQGnExJNUv9Rp6tvpbseGpBtUhKY3WSRFybhboMYPpqYu3HXgNkp2aNYA9c4rVjEMH3jNG1iR2lMXtbi6b05QSxmEW-XRE76SMND9uPMZEGrN_FB05kg4gOk7sAIGm8cqbqk8qLWoXF428K1p5SKSyhvCtCipIyE02Is0fBuZirS6A5TkbKFg6RNInMMV20WmapqYL0nFo7I_pYUQ9U3xZ_pCmZFRer2cWEMZModsbyfxN3ECWKJ20dfU0vcMQDSkrjiLM8QVvsJJa5T13NF9wnNSM8Eg_ts4nYwrd_u8fF1U-K2umHJNJrZMHz_QbGyEN7vsWJlx6JP9Nuy1d0m8vB1cgjUShx7dXlGv7kRcUgPOjmfoYyI8XMixlVfuEVM59NQoI6rjA_WL5bU3AJr2eSSowR81z_kk0puNCp1KxpK0IrQDrwGoBavo3Fh6Z7ViGbNG1onaDCcJmA4WR3O1CwwoXnvqCbhWsHV8HSmK25zxYUmIWa6Slgsh2mXpjRdFWTo6tbx2bCsa93AaTuERGt7wXs40dX4VU9V0Y2nEIHa7iJQE7KlvEs6mGu6TAxBcQdX9VTRsfyGz4_G2C2q6xeOE3Bpt7UblvakreJIIp5r0VZcq-AlZ5RB2qhGbF57RcV4W0L2FVMhSG805WJZVO5vaiWIEo_3NtmitHa2KCRp4MdCzNJF86HQlK10Tb3aO9oLNRpxHQE0NEMyTH7xjIbLn3aJDhuypCJjhInQ3vclWoEbym8FeXWmcQA0fHcKMhUReG2dy8qZbpXNrS7albaRDE_hNBAFB3grkKXoHGLJWyFWEXG8bOnTRxNXZH5H5mi0UpQLikynhlSkCoUihlanp9JpgVaGT_eWiNGKYwpZgFYwmpOBFdNvJGlrsNJUFY91NAB7S_pe2wnaatRWOMSlyxP5EaYNdc4wQx4LRO38D2J7pi8w7BaJB7S3rhQpxitAGPPVIMxe639thJFNGev69urQTggjm4aJ0daG2hYIgw4YYdB4hGmmUhAjTJ9C0x_Dn61bwWPLOA0tQmg53RHvetltHifzH7VjcOuNPxK_leUc2hb5ji30D3dPWjRckZ1DqJznGREyk1qR6ktvHseo1WPDDMVXOsRfQ1SMJNSVkO0kC82thWOX8jbtaio8xqLtcqI9yHn-eDW8rZg9QbenrLPFoAGvH4pvu9XQKcSUzIspQNntbHdupQPpCg2zX8kpODFrsROzbVlFbyUCG7662ZRZVXWc3FKatjzsjx86BN1rwpsdE55gduHlxj4ezC6BOZZSDIHMkqfds2LokF5lT8ffePN6K6HTOqsgOkTfa3aTUecGU0GGSBZtbXYvpjO72-cgxGb3FCnkB7z5hww0jSV7LHISysp4pEHqgvPcqKpqPDPQqPsCDVLPtO6etzNtSqChQzsh0igqVpG29e643qX-3RcZdsWRPlKZeu0B7772gMXQob1DB4UOZas8VdtDh96gB_N5oUPTJ4AO_cmhY79MVR3owIqhqeb2Ru_PAx3K7tChiKFDnwI6RKmRXxF0TGneEHIweHLQpGdGDnMC5DCeGjmmtW4UyZA1rUeP2Qs4lFcOHN5YQ6Ydc1gIHOAcGL_fAdoZLvyYDmD5rwtJ4EmLlRMZn8iSDDu4lp6dr1NG-ITpZ9k6SeI094Brzj7_djVbkmlYwUSXBeTKje_96GZmB0F8T588v5gt4jhvvH3lBZ6Tw5vde7Si33-7nGWxc-uxsk8XF7Ms8ZzGg-hYvjybff10PjMNSZr93U7syMu82d-COEkeex79I85W_sIefBJr0u2ZuIqeG7oseEM-Noz-V76lhGNnV07qeVFrXCg8k38odXRf8tL-m-e_nJ5cxlE8-6fvenHj1un5t-bUAX988W5s57E77mcwG1fNkb5mARcCBshpHFosUzHSdF2XwbeY5XaaW9WBubn0sCz8f1U4k9MQziTYEMPlxs5TUpzNioA3gP128GH25cv5MX0lZb6NuSwdIxrPoojP9h_2oyucuAiPlzGcumvFZKIpG50VwQw_Y1lVOcqG4HtAsWfFO797SUCglJI113UiXoOYuYzJZ_6IZ2eEfnyCMO7s7HH22_Gn40toPRFsa_BYk9ppt69-J1T8OzvQSUSYu3YgafOZpqkXyvcj9KXRYXxMcAyaCmKdeTAzwgU--eodDXHR7882ju7tR0IX-dFp9Th3PFMva-wOHLdP83vkL32P98eT1zzH6WzA4HcjHi187ngj7MloAX85ekTMBN6dx2LO1OPY7y0uAyE1ncQgTEUrjP8Lgmh21jg3S51ghFAtZ50SesvLrSq0LLQfqmsKM6SSL2h2NDunQ1-WcotKZWgR8iu1QzqUdc0EH_3EC_yINGKdEj3omn-sZqWeB6lUfSOzbFazjF5wltkSHDfNRUE1z_LhzTN3ng1pwxNtHMBEI6maafkFZxojCVzp3FSXJdVc4xeZ62tO3ICuTaQqUdmImMw9kdZ6ZS9bgYGKGrrTzKcqL9ZEGy-Ws4Tp1NxaRPvOaJeKbrdklFCWxbAKS4Q5NTOINpeO7QEx09YQm2n4va9x1HoPRHhoB2M_VwtSQZdgXgJieqztGyZeK-Fu1jeKc-___X71Xz-LDUM1jxCbUhZtz7LT1GYx_nbgpzSNU6tiI8yxlCJgJK7LvcoN9JwQf6GUkekqoonPmR2VUY_cOqNdFowkOygatqLr4R_tThMmSxLPrTU90FDoDb4XRLdr6IKyVP6Zc91VaeCu3Lr33XxF29jVIqU514LSbOv95sKObi1OP_smzc5_Pf369dOXGSyyk4kqwoAZnTkg-mtjnwE3Rlzw64vPl5f10Jgcl0FAFO7L8OBM6mqCl76TxlGdXBsGuuhZm8F5A-43mHFuTsDfwr1mMa8Kpdmrx8hZkW_E7AgRHd3ScJ5f_nEuS-Q_Q71Cn84V4-wUzf7-N6ARwEmJgSipH6uqQhPHc7HpP8yLSYK4xhOPvrnn6MtSd_TR--gXo382PPqw3Lnf6ON32t999NV9R1_7mWi_LQnEwojcsHg50xZIqFcgGUUY0cCz76B3CXyXnvviipM484tD7XCn2SBeIqTxffvhXvn2Ya9Gy2iyRsvSEzS6V_SD0T1Vo_GWjeZGb9_W69O1Xtuh9TUbUDThyJ5_w6gbXnxUcJdB0pCJ8ds_mrrmTUrgJShirvZvV6xjF3MbFnmlN068tKvpbqqhjOODFF0xsEYXgh4jN41DZlK-toHQ3geiUgLfB6LQx94HolCNnmQgCHrGUZ3upViFY8Z809VVfEToHBkaDroI0zaky75RTSZJY1hILfCbufPYA1aAqK7YLJOpc7VZhpkfzqE-Hu-BOrira-oOU3VV4tgMdZcn3Ds7ckjPqI44u2DD8WH2OXKgj6DINQa6ajbRWUM_aEwun3ynpTsiCbzT9cvg11kLjwt9Kiai4fmrXx4a-PNv31seqNIReHqpVh5AInATQp15PdlFebtqxRR2SW86nGCF__fHv7xoZs50U5X-hS9mSDs6j1Nv9q2a6-bphmpeOtPyq5f_FbG9E9WS0Zz_HMvzcW_fetY6EbmgvoHLbnZ178PCO-eF-vGjbsX8wdAsTTkKIFsS_wkIcOGn-doO_Kw0MCJw1AGP-TernPUgde_t1OMXku0krEPfkzJrGdg3WfNIQel-pWvsxQfBEKh9qsUT9V3y2WBhl27X6oGAqE-FOsTMCAj2EiX1UaCIrZRL5Zp3_UFdh4A5C69qLd-UO-Bgq0znQXOPLVLfLdyGzY034nMF3GScsbcbzsBJYuQUzerfYDMYHwf17a7pRutQejbXKHjJ5Q6Dc_8av7uGtMyj09TdXVPectO79t2s6FR1v7nHpqq03mODW-FxYJPCohzobU4PKO3TAxjLxsKRtMyRFBYNRHw-h1vh-BqDv3rmkpFzW-kx9t51c73Dfv-t9to1Ka0eOI7g-rbLwBBxn8aSWZ7F332vP953r3_9avvc2dNGxXpxDt_qeNBO8Sa5w4UqxrDqWHKd0eQ6mr1we7ZDykVxzhT-MLaDPwXbFcHwREGnDCE5c-zYbBHHjKKYjsbI_VlienvasKeHRW6iQyK7kFsj-hNWGvHWbpFElJW-yI6CO1RelPeaUoQrLcnZ3JOcy5hSu5CzrDwFPSNjzBmH5tNt_JziRNRrIWg0JUGjBkGrNX4qaF-CQwdIcCMyFjWf_pkJ7nkEtoJfUGCjJxHY49JpoiEFcQJyAzvkUOlt0xmL0gqEOEUDNKf3W4Fq0wpshkl9JitQ2dcKVF_GClS6B6ymtQK5gxOykAsPyApUwK6b5sS3PMTxP5OO_kwSRn9BCfMkGo00KliwNBQseIrTfQdMbuBheQqbUDclfn-nZJpcKB2l5YP4fHU6gt5I1Z96omN_KugNiaNjqxyUGR3A3S44Np_ymW82D-P9EbJ7xmPqCNlj7EZlyG6cQq86ZKpvqVVt07FUq_BwKGzcD7SLBtCaL6FVqdI-WhVB9E78eaSo-Om1Kjwm5O71AANPrTFB97lplSU8NfuCPjROexKy7xv3mm8Kd1Nxrz7IvahvbYywL3_sBivoRdhX3pN9L3qyQF08A_uOCUI7wL7idYKd2bdnWqdl31FeW2nQa7vLwfBXxL_SNmkodvLa8pEAsMppnOq-TrRP2gF6bUekYWg-_RRe2zfhRtOGJYYgEuMh-NFU5ZX60brRTZ_Mjza5WHkiP9q4BW2xH21oqVt-667zrXZPwfLxEMPLB8zw6utkeBjy52J4hF8Jx7vTpSgRc_wUWUlei1o5qeecD0WGscapldq-nvNujDBStp1aKfZRbqVV9ltJ3a5OnX93DKEP7Q1840bS1i7KDSqrwEd5CE4O_ZU6OUZqrG_LyTHGRzm0U2iXZH-viH2lbYLq7uTjUBpTzC3jqvvu7P2kHKCPY0TM1ubTP9nOtK2d4sog0fUZPAeypGW-0iWtMYHhB8SFeCve4S5poVE-cTTgE5_Cdjlkb8XWHsphmaEdrr9CQ6_TX6GMTKe0l7_ilbgrxm3gFbsrBrf2vvGdVy-w0U-TX3Cjn9gVt89GPzyKEvEAvU2RAeS1kJs8pUEi8-SmcN4xTdnXIJEP0CCRRxkkshjffjKDROjAwsMOrIM1SLS9FmBe0CAZk27mzRkkY_xXaMB_9b5lojBIhrfImgdskLzWk0cj98juY5CIhehhGSTjznuIDZKhkyDyG19xejKDxONyGRENUeE0xL1d1tIBaogjSBENbdF589vypghwhPoUxAORMPpepzBeTsI8eYQj3uX1Wg63OtOlMxaLmLfO8dtqlXiY6dUD5vm9jm684La8Z-T5VxHVTJkug_lgiLOfye_4PG5ufV-_4z5ubrE428fNPTaygpjelJ-I3PQpjRg-kzVWEUdu6r5GjH6ARow-yojRxfj2rtIUjrLhjTfGAas0e23UfEFH2cidN_uoNK_loMG49VKxSjO0kop-pr2d6pQyhuN2FSsmJ2P2dpSpByhj1FEyRhUT3C4yhsytk6xZRHCWOYEGIaf9S1aPme_YMNrSA0vFzsKplwWkW3bqrPzco2Hf52UodiCd-IaQr4ENfGwgIMcbiquk5amXW-QrhMwJ1H6ATElOnnrWHeIv5OLCyvKYXC8eExhzUpZmMdBjkV2YZb9lKQXIvN9EIc0RCUvuTrAM1tmqCKlOS2KaLRlMDdJl37XKPK-QPa9IBUDzWXGJlZdkbEi3Q5hMCrZJBn_nmQMEl9Hw9jYlPgf-dh4ArezEh9uZB0FdwzylTzESdUBdd8L4jr6Yswox8HLRXngohCj2ywdae0a_R_6GEVnlbPLJnEAi0uiBPQ15E9gLVpzQOt3EQzewOJy6pKnQjCCEb8RRlttRbrH2p15i3cQx7Ja3QzIci5QNfBQnUP1DHidlrq0I3oyT4kU6fORf8mHXgt7SKzshciuEv6Bum9aRRD4Va0G4Dv50_6RcGvmQKQw6ldGIucuQDsoD0lhPFQuVP2T6wt2CjnycOBH0zvaAEh4ym2aUte_oaCGN9shNAZsgEeZqabE-hwmZaMgUDpXehazZxRQ5qVHftBdh8V1oT-hnlKLYBGA3iu-T1Ft6LBFBnN3dk3_8BSXKWz-iSTLvXfg7p6QAg8cmBkaEULUF9MddRjA_i6T5TBBQwrq3_fyBDjQ85Ng5ZMogP9yE_VjdWwlLLAoNXkCPw4Vd1ENGmM2jv6Ac5i9oLVlOfhSllhetaNIMStxhQU_L7CajOgNpV-gjNriUE0NKyqQQrrw0pNVGdwmbeOfPkJGaZbN3VCQvq1901lM38-jXbPeBVmgn1QN-QQCMARgFO8H9onrAgRezlW1RYmJli_vq511QkgN7l_6EYXy48fIFxRValLGmFmMMv2LHIdhZX4eLkEjdnGb5La8hOR1crzPIHbvK8tvqw9ZiiRjr_uWlkCvFTwvqp9_z0iRPad-TFFDkfhHFZNDoiCUJfNNOKQREtNmE_e4YicI34StR6idWQeaE8SzgeypVQgekkGdDOhM6aItHO6NTwZRCmnM3zyjGkHYv_SBnmTiW-YoA2yoO6FTcUR64u_Fpk-Xy2qLAS6iRJjuOwnrQ7xb0Yh36NPg0gGOhUZKflvfgeAlTB1hhIapNCEBTiJLyzBpLxUsUCfvGC4tUxbTBeQ6EkYeUyCsaZ3zgLZfWMvX-tOhg_xvha_qPck3TGvuLwI9AytD8e7mXJOSS7lDIg0UhBrAKWbTXEU1miCt5aZXycZ2vSGN8hwnKe8jgbBH9BeRbkY4DBKbrZ7fdHBoQCrNXV0ONnLrk3uyKACDpeJGrZl6JZFmTBaqbyVXx9Z-Xn-p3EA3w0dTeaANJRTSLjlt-JAIxdt3VuGxDsuvar04vr75__WV2-X__80VGf5i_nv_99yNJOpU4y1_BEjJ4GywqJGTL_uorpmK1akptcZVFhapncItGg01qmjzOYwAVQJXIwEiB1eobLy7Gc06kmc_YGbTVjOkFRCkl81ESTpmBGNSd4i0YTovUQtPuFWX0OUZKcFVUUYwQEWAfsa5KumIYEOWPFcpEnUUy3UvkpT7Voq405Zevv0j_UmRT0an3YJ9Trhds2jccb7VtyeanUsXCGHyKwp-kQ9TubumxMG21DVTk4CJzcLvJqELHuLiQmVEFNZ00q2P6MO3zCSVmdj9CbOQfyu8V_YfvDTxByYw-AxN6sng88l36-FFBYFaXwKzODO1XAVVteqvw1v4x1rCi6FgiKEWfliRZxYaiF3aK1n6XaJArGNwjfiCPaHXVd8rxuG4NSEFY_5mH9v-DSZfpySI_or-rHGSVe8AEft-CQDoWrGK-w-KEsIh-Olg0B2Bxq8DsLwWLaDdYLH1NqAWL7S2bbVhEG2Gx_4n9YdHcFxbNUbBojoRFJIJFNBIWpT1g8ZomlExWvpNZTpm6sZmDTRf6-nCDmJPAfpwRUz5P4yBopLfe3-_XbCN1SAvcf3ibFU1teANDr_9PUzjoV3XExa_T-fh1f3ye_fOXUzIQIZlvovx7zTERewOlwhuoKVUAZancek7KFo6Ea2_gVh550o4mwDTR13YclpE0JWNkUati_qHwzqs67nHQlxlAIbJK6Z5nOMve0sZsU_jQbkEcBY9VA5BkaJJhGqpi6t2QDpXLAzInzuuGaQZBSIVrXuiF23yJGGCyKdEU6Vt-STJ1BIFAB7_THFMFYU3DMpa7ZxYFX1FlRTaM5kcESyGOySkmUmcxBG2Vtq5JO0Ia3iCyelml_6QAn3MWOOcPz1lF4NzzvQwypXKYIFFM63VXu2M3gxiVNGu_2t7y1bsgP7LVNEPtetGFVk0ErYhX8X5dc8dpZE20imJwOuf3qzNO5cRdPF1nUCc0qoGihbTpEgaXrHXFN6c-QED9EbETBxSCizIy6YNElhBkrlGsQVhVMYFK8iuyc1Kdl-fUeSLx98e1tn6vYge-sO5Fo3jnjvRIkqbgfPj1_DNbMDoXiM5KbWd9aWvtZCoLD25XcS_vNXX3YtpXcZ4E6xtWxbxW5bktcl8gde1MO0bKMZJmDyuiu6wcdyZoc0u0kVo_3qEL7SyBHruShhTXkUwXhJibSNgnFz6VaOQBPxLmBeDHGZrSAqBSOef4WdnksWiCiHYkfRx3ZrqFH8oJ6at2UtfTgQyXz-DcP6p1t3QVox6DVX2TYIHewWIDWMjbgoX8AmCBnwIs5A5YoH6waOwqoc5zieVkz1b2LdP3E5voYI9My09greejYhQGGrjj48SqXiy0rIW9dsU7TkaDER4HRnhfMMIARvgEPykYaWLv2TsYvYPRC4GR8g5GYjDyKktnezDSdwCjcvmEfQ_ASD_R3zWjdzPqJzOjtFdvRo3UXJRJNBflRHnXXN7B4oXBQsTU-mtm6l00AGMSDcA4MZ5WA1DeJFO_myOv2hwx3s0RMRgtdgAjNBqMBg_6n_AtAZhCJ-hpdY-3ud7zDlOvGqbMd5iadj1JnWQ9ST1R33Wmd0Po5_KamOg1G1i76DTyE-s08ok8KYyQubv1Hhdx715BUHkFmGLUH_pH-T4HLMoUwHJbVwxUtR26bIcIHZyRXhpnODZe-W6Ta7fGGbQRZ1D9GSJU_ZibgX58kbmuf7uS85hM2-zUtZO8gS0NTYfMFutDgSJ-tIyhzkKcc_P6cLuwSoBIHES3kEJZylBn_rBMPY8QzY9erGp8pAlVcKuJVHWhCKy4s0C_nF59Pp319LcPl6RPxt8SGCmX_I9cgKQClySCSxhwCfmgMe2lJCF1EhVJPuajLEjtjYVjDwN1mb_X0ENPbujR_4uviHan-1Gyzk88gpt532P1FnX2INsfTuo_ouRgleRgFeRwRGs6uqUHY5vvtfaGs6YeQVUEvKGVu7x7J296u-ja9Ybd5rB7tNhsDkcwit2pqNptDrpNW7hInrGsp50OCMf-usw2n4deGKePXUkiCjCBeED6HFHQDILH2ffMc2fnATuNX0oVVe-IiOJ71xUTYy4-0KXtR7NL9sSYzdKD-3nX0W0U38OR2HLYsCIZuqEpdCNwa_9w9YyuYMNUsaLXe4zhsKpV7gHuZzTO0Gx2prIv6aDHa2j2COmtcvXSlznRjaYQ3WFRayG32c7jamfx_BcvIqqWMwNsLRtQPFPS3fx7NdDvUr88h9Qv9eXDlvqLdZ7HEWnQEXiWFhaBqPTRkoBMvIckIDZFmmQn9Mj_Q5LJQC83SUgqZJc1TxWEcr_yvKCo7mFJyPJjs57n0BUM9Wl1BZnoCuhN6Aq4gRqzFtxgkbIwJnPA7srC0FE2JlFDdnqz_ZDcegp6tY1KQasbI56xQDx3K5D7a8DypAI-8vL7OL21uAMk3XMQSHjEjBNoX1lNvUdRRAdxRxwx62no0DmzTYHlyqNmG3LY9x41UzGfaUORG3Hl_Js-R0xPKSUlKG9CVVFSxnjnbBhQp4LZp3xFZJKXb3dszSBinh1RI40ujq0ZiplVZQtHkutjay2dikV2YmcMC6xZ3UPpxrNUGlJ6Ur8VdIvl_uNpo5Lbbz7MZeq6ISndI28jDnNt_IgiYUnGPUmNBR9BGoZtkO1v9Ax0Uo60CNdxC3V5JNdGWn39RLXpHFkfH_SeIyMUVz-oyajn5DNDdW26sMGoumhX2pMqr0dmeFGiZUIRUNy97sKu0VCsGc-ex2kSpzZFIk7ZMiW5gcHcgdHt7S29i8Cfu3qtrGEhotafrXHH5E8ZxXGysJ3bWfHCjNebN5JW-XafQ4E_kU4qPwnifvndW07ngdy57q7jPttoPRHqm9yxjYo1-0Z_HF5vQJn-qURdlOCtjR1iFezCsy1CETLn1owLHQbtYcx5ek5ZuVwHuR96rm_3QqbIXT46lGbpnehXcvRtYmkidYfT9GojMaEmNQzDLHKtNAksOORuO4n20EP6G5-hs9F9qskWvfcLJlFa-UFEU7I5vqdapkrkksmRMqIaKZlj9KpGxdF0da8D9R2NRUeqpklbaywyEaWKstXxc42bTnZQe_Tpc0PamvyRbAh1hh7CmjBLHV2fHxEZtb20Lw6TCmldnjAuL7f-VjrTSDtyL5wl5CIhwEsD7RS1G8-DLyxO6ubMp3inFAScTkg0Sf1Hnay-lex6aEC2SUhgdlNFXpiEuw1i-Ghi7sZdA2anVI9iDVzjtGIRw_SN07RpHaUxWVmLp_fmBLGYRbxdEjnpIw0O2Y8zk4Ws3sQHTWeCiA-QugMjaLxxpOqSyotah0bhbQvXnlIqLqG8KUCLkjIQTouxRMO7malIoztMRcoWDpI2icwxXLVZZKqqgfWeUDgi-1tSDFXfFH-mK5gVFanbx4UxkCl3xPJ-EncTJ4glbh99TS1xxwBIS-KKczxDUO0nlLhOXc8V3Sc0Iz0TDO6zidvBpH67R8fXTYnb6oYl02jmwvD9B8XKQni_x4qVHYs-0W_LVnebyMPXySFQK23s1eUZ_eZGxCE96GR8hjIixs-JGFd94RYxnU9CgTquMj5Uv1hScwusZZNLjhLwXf-QTyq50ajErWgoPStCO_AagFq8jsYFpXtWI5o1b2idoMFwmoDhZHU4T7PAhOa9o5qEawVXw9OZrrjNFReahJjpKmGxHKZdmtJ0VZChq1vHZ8OyrnUDp-0QEq3tBe_hRFfjVz1VRTeeQgRqu4tATciW8i7JYK7pMjGExB1c1VNFx_IbPj8aYbeorl84TsCl3dZuWNqTthGTSOHX9tBWXKvgJWeUQdKoRmRee0XFeFtC9hVTIUhvNOViWVTub2qlhxKP9za5orR2rigkaeDHQszSRfOhyJStZE292ruy1xJdI64jgIZmSIbJL57RYPnTLtFhQ5ZUZIwwEeTtfGqD2a0gq840DoCG705BpiICr60zWTnTrbK51UW70jaS4SmcBqLgAG8FshqIJW-FWEW88bKlTx9LXJH5HZmj0UpRLigynRpSkSgUihhanZ5KpwVaGT7dWyJGK44pZAFaTQpWTL-RpK3BSlNVPNbRAOwt6XttJ2irUVvhEJcsT-RHmDbQOcMMeSwQtbM_iO2ZvsCwW6Qd0N66UqTorwBhzFeDMPqUCCObMtb17dWhnRBGNg0To60NtS0QBh0wwqDxCNNMpCBGmD6Fpj-CP1u3gseWcRpahNByuiPe9bLbPE7mP2rH4NYbfyR-K8s5tC3yHVvoH-6etGi4IjuHUDnPMyJkJrUC1ZfePI5Rq8eGGYqvdIi_hqgYSagrIdspFppbC8cu5W3a1VR4jEXb5UR7kPP88Wp4WzF7gm5PWWeLQQNePxTfdquhU4gpmd-zAns4t7PduZUOpCs0zH4lp-DErMVOzLZlFb2VCGz46mZTZlXVcXJLadrysD9-6BB0rwlvdkx4gtmFlxv7eDC5BOZYSjEEMkueds-KoUNylT0df-PN662ETuusgugQfa_ZTUadG0wFGSJZtLXZvZjO7G6fgxCb3VMkkB_w5h8y0DSW7LEAaFRzPNAgdcE5blRVNZ4ZZ9R9cQapZ1p3y9uZNiXOqNPu5ldUrKKeBDZjFvp3X2LYFUX6KGXqlQe8-8oDFgOH9g4cFDiUbXJUbQ8ceoMczOcFDk2fADj0pwaO_bJUdYADK4ammtsbvD8PcCi7A4ciBg59CuAQJUV-RcAxpWlDyMHgyUGTnhk4zAmAw3hq4JjWslEkQ9Y0eb-thR3gUF45cHhjjZh2vGEhcIBjYPxeB2hnuPBjOoDlvy6kfyctVk5kfCJLMuzeWnp2vk4Z4ROmn2XrJInT3AOuOfv829VsSaZhBRNdFpArN773o5uZHQTxPX3y_GK2iOO88faVF3hODm9279GKfv_tcpbFzq3Hyj5dXMyyxHMaD6Jj-fJs9vXT-cw0JGn2dzuxIy_zZn8L4iR57Hn0jzhb-Qt78EmsSbdn4ip6buiy4A352DD6X_mWEo6dXTmp50WtcaHwTP6h1NF9yUv7b57_cnpyGUfx7J--68WNW6fn35pTB_zxxbuxncfuuJ_BbFw1R_qaBVsIGCCncWixHMVI03VdBr9ilttpblWH5ebSw7Lw_VWhTE5DOI9gQ_yWGztPSXE2K4LdAPbbwYfZly_nx_SVlPk15rJ0jGgsiyI223_Yj65w4qI7XsZw4q4Vj4mma3RWBDP8jOVT5SgbAu8BxZ4V7_zuJQGBUkrWXNeJeA1i5i4mn_kjnp0R-vEJwrizs8fZb8efji-h9USwrcFbTWqn3b76nVDx7-wwJxFh7tqBdM1nmqZeKN-P0JdGh_ExwTFoKoh15r3MCBf45Kt3NLxFvy_bOLq3Hwld5Een1ePc0Uy9rLE7cNweze-Rv_Q93hdPXvMcp7P5gt-JeLTwuaONsB-jBfzl6BExE3h3Hos3U49jv6e4DILUdBCDMBWtLv4vCKLZWePMLHWAEUK1nHVK6C0vt6nQstB-qK4pzJBKvqDZ0eycDn1Zyi0olWFFyK_UDulQ1jUTfPQTL_Aj0oh1SvSga_6xmpV6HqRS9Y3MslnNMnrBWWbLb9w0FwXVPMuHN8_cWTakDU-0cQATjaRqpuUXnGmMJHCjc1NdllRzjV9krq85cQO6NpGqRGUjYjL3RFrrlb1sBQUqauhOM5-kvFgPbbxYzhKmU3NrEe07o10qut2SUUJZFsMKLBHm1Mwg2lw6tgfETFtDXKbh977GUes9EOGhHYz9XC1IBV2CeQmI6bG2b5h4rYS7Wd8ozrz_9_vVf_0sNgzVPEJsSlmkPctOU5vF99uBn9I0Tq2KjTDHUoqAkbgu9yo30HNC_IVSRqariCQ-Z3ZURv1x64x2WTCS7JBo2Iqsh3-0O02YLEk8t9b0QEOhN_heEN2uoQvKUvlnznVXpUG7cuved_MVbWNXi5TmXAtKs633mws7urU4_eybNDv_9fTr109fZrDATiaqCAFmdOaA6K-NPQbcGHGBry8-X17WQ2NyXAbBULgvw4MzqasJXvpOGkd1Ym0Y6KJnbQbnDbjfYMa5OQF_C_eaxbwqlGavHiNnRb4Rs-NDdHRLw3l--ce5LJH_DPUKfTpXjLNTNPv734BGACclBqKkfqyqCk0az8Wl_zAvJgliGk88-uaeoy9L3dFH76NfjP7Z8OjDUud-o4_faX_30Vf3HX3tZ6L9tiQQCyNyw-LlTFsgoV6BZBQhRAPPvoPeJfBdeuaLK07izC8OtMOdZoN4iZDG9-2He-Xbh70aLaPJGi1LT9DoXtEPRvdUjcZbNpobvX1br0_Xem2H1tdsQNGEI3v-DaNuePFRwV0GSUMmxm__aOqaNymBl6CIt9q_VbGOW8xtVuSV3jjx0q6mu6mGMoYPUnTFwBpdCHqM3DQOmUn52gZCex-ISgl8H4hCH3sfiEI1epKBIOgZR3Wql2IVjhnzTVdX8RGhc2RoOOgiTNuQLvtGNZkkjWEhtcBv5s5jD1gBorpis0ymztVmGWZ-OIf6eLwH6uCurqk7TNVViWMz1F2ecO_syCE9ozri7IINx4fZ58iBPoIi1xjoqtlEZw39oDG5fOKdlu6IJPBO1y-DX2ctPCr0qZiIhuevfnlo4M-_fW95oEpH4OmlWnkAicBNCHXm9WQX5e2qFVPYJb3pcIIV_t8f__KimTnTTVX6F76YIe3oPE692bdqrpsnG6p56UzLr17-V8T2TlRLRnP-cyzHx71961nrROSC-gYuu9nVvQ8L75wX6sePuhXzB0OzNOUogExJ_CcguIWf5ms78LPSwIjAUffjx_8Ht0y94g)

**Comment by brianmcgee** [comment]
It's probably easiest to remove those fields from the report, as they don't appear to be of much value.

**Comment by brianmcgee** [comment]
@DavHau I looked at your diff and identified some changes which I made in https://github.com/nix-community/nixos-facter/pull/208

**Comment by brianmcgee** [comment]
Resolved with #208

**Comment by DavHau** [comment]
I don't think this is resolved. Best ti implement a VM test that executed facter twice and compares the results

**Comment by lucasfcnunes** [comment]
It's definitely not resolved. Can you please reopen the issue @brianmcgee?
Regression testing, as @DavHau pointed, would be great too.

**Comment by brianmcgee** [comment]
Happy to reopen. PRs welcome though, I'm not going to have time to look into this any time soon.
